services:
  postgres:
    image: postgres:16
    container_name: uptime-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: uptime
      POSTGRES_PASSWORD: uptime123
      POSTGRES_DB: uptime_monitor
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: uptime-redis
    restart: unless-stopped
    ports:
      - "6378:6379"

volumes:
  postgres_data:
